/*
 * Blog for service computing
 *
 *
 *
 * API version: 1.0.0
 * Contact: 895118352@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Blog struct {
	Id uint64 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty`

	Content string `json:"content,omitempty"`

	Review []Review `json:"review,omitempty"`

	Label []string `json:"label,omitempty"`

	Owner string `json:"owner,omitempty"`

	Createtime time.Time `json:"createtime,omitempty"`
}
