/*
 * Blog for service computing
 *
 *
 *
 * API version: 1.0.0
 * Contact: 895118352@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
)

func GetBlogByLabel(w http.ResponseWriter, r *http.Request) {
	data := mux.Vars(r)
	label := data["labelname"]
	fmt.Println("labelname:", label)
	// FIXME: query blogs by label
	if blogs, err := DBgetBlogsByLabelname(label); err == nil {
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		var temp = Label{Labelname: label,
			Blogs: *blogs}
		buf, _ := json.Marshal(temp)
		w.Write(buf)
		w.WriteHeader(http.StatusOK)
	} else {
		w.WriteHeader(http.StatusBadRequest)
	}
}
