/*
 * Blog for service computing
 *
 *   
 *
 * API version: 1.0.0
 * Contact: 895118352@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Label struct {

	Id int64 `json:"id,omitempty"`

	Labelname string `json:"labelname,omitempty"`

	Blog []Blog `json:"blog,omitempty"`
}
